services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d admin"]
      interval: 5s
      timeout: 5s
      retries: 10

  db-init:
    image: postgres:15
    depends_on:
      postgres-db:
        condition: service_healthy
    volumes:
      - ./db/backup.dump:/backup.dump
    environment:
      PGPASSWORD: admin
    entrypoint: >
      bash -c "
      echo 'Cleaning and restoring database...' &&
      pg_restore -h postgres-db -U admin -d admin --clean --if-exists /backup.dump &&
      echo 'Restore finished'
      "

volumes:
  postgres_data: